version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: geomirai
      POSTGRES_USER: geomirai_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=geomirai
      - DB_POSTGRESDB_USER=geomirai_user
      - DB_POSTGRESDB_PASSWORD=password123
      - TZ=Asia/Kolkata
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pgdata:
  n8n_data: