version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: geomirai
      POSTGRES_USER: geomirai_user
      POSTGRES_PASSWORD: geomirai_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - TZ=Asia/Kolkata
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=geomirai
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=geomirai_user
      - DB_POSTGRESDB_PASSWORD=geomirai_pass
    depends_on:
      - postgres
volumes:
  postgres_data: